### ISSUE TITLE
Add a `WeakSender`?

### ISSUE THREAD

**Issue by phil-opp** [zesterer/flume#107]
[Weak pointers](https://doc.rust-lang.org/stable/std/sync/struct.Weak.html) can be useful when working with reference-counted values. For `mpsc` senders, this would allow to create a clone that does not prevent the channel from being closed. As [`flume::Sender`](https://docs.rs/flume/0.10.14/flume/struct.Sender.html) is [`Arc`-based](https://github.com/zesterer/flume/blob/8bb9ce02d3502134cb23cebe3d389aded9f64d15/src/lib.rs#L655), it should be possible to implement a weak sender type.

Some other channel libraries implement this operation already. For example, `tokio`'s `mpsc` senders have a [`downgrade`](https://docs.rs/tokio/1.21.2/tokio/sync/mpsc/struct.Sender.html#method.downgrade) method.

**Comment by Restioson** [comment]
I have something similar in https://github.com/Restioson/xtra.

I think that the implementation might be a little more complex than just changing the Arc to a Weak. For instance, what would happen if you had 1 weak sender and 1 (strong) receiver? If it should drop the channel, then just having a Weak on the sender is not enough, since the Strong on the receiver would keep it alive. If it should not drop the channel, then there is no point having Weak senders, since they would only affect channel closing with no (strong) receivers, in which case the channel is already closed.

**Comment by phil-opp** [comment]
The channel should be closed when the last strong sender is dropped. The custom drop implementation of `Sender` already does that: https://github.com/zesterer/flume/blob/8bb9ce02d3502134cb23cebe3d389aded9f64d15/src/lib.rs#L746-L749

So I think it should be enough to change the `Arc` to `Weak` and skip the `sender_count` increase that normally happens on `clone`: https://github.com/zesterer/flume/blob/8bb9ce02d3502134cb23cebe3d389aded9f64d15/src/lib.rs#L732-L735

**Comment by zesterer** [comment]
I think this should be possible and, indeed, relatively easy to implement. Out of curiosity, do you have an example of a case where this might be useful?

**Comment by phil-opp** [comment]
For example when merging events from different sources (e.g., using an `Event` enum) and only some of the sources should keep the channel open. A concrete use case could be a command line application that waits for `stdin` lines or a ctrl+c signal using the [`ctrlc`](https://docs.rs/ctrlc/3.2.3/ctrlc/) crate, where both types of events are sent over the same channel. We want to close the channel as soon as `stdin` is closed, so we could use a `WeakSender` for the `ctrlc` handler.
