### ISSUE TITLE
Why does sending require T: Unpin?

### ISSUE THREAD

**Issue by Darksonn** [zesterer/flume#66]
It is perfectly valid for `SendFut` to be `Unpin` even if `T` isn't. As long as you provide no way to pin project from `SendFut` to `T`, having a `Pin<&mut SendFut>` does not imply that `T` has been pinned.

**Comment by zesterer** [comment]
Thanks for noticing this. I've pushed some changes that use `pin_project` to allow us to circumvent this requirement. I've just released version `0.10.1` that includes this change.

**Comment by Tamschi** [comment]
I just stumbled across this too (in the changed version with `pin_project`) and it gave me pause.

I don't think this crate needs to be pinning-aware at all: Even if `T: !Unpin`, `T` is _not pinned when passed by value_.

Since you later release any `T` also by value, you can't pin-project from any of this crate's handles or containers to the contained value. This means there is no opportunity for pin-requiring code to run until the API releases ownership of the `T`, which means that at no point in this crate there are pinning requirements regarding any `T`.

This in turn means you can implement `Drop` plainly and don't need the `pin-project` dependency at all.

(As an aside: `reset_hook` potentially moves the values around. This would be unsound if any of them were pinned.
`pin-project`'s pinned dropping is a utility for implementing `Drop` in a way that requires pin projection. It doesn't change how the code is executed and can't prevent moves of data held by containers without pinning functionality like `VecDeque`.)
